version: "3.3"
services:
  app:
    build: .
    image: nodeapp
    ports:
      - 5500:3000
    environment:
      - MONGO_URI=mongodb://mongo_db/nodeapp
    networks:
      nodemernapp:
  db:
    networks:
      nodemernapp:
        aliases:
          - "mongo_db"
    image: mongo:3.0.15
    volumes:
      - "mongo-db:/data/db"

networks:
  nodemernapp:
    driver: bridge
volumes:
  mongo-db: